version: "3"
services:
  this-box-server-api:
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - "8080:8080" # 포트 매핑(호스트포트:컨테이너포트)
    container_name: this-box-server-api
