# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle
name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Test
        run: ./gradlew test
      - name: Jar with Gradle
        run: ./gradlew assemble
      - name: Docker Hub Build And Push
        run: |
          echo "${{ secrets.DOCKER_USER_PASSWORD}}" | docker login -u "${{ secrets.DOCKER_USER_NAME }}" --password-stdin
          docker build -t this-box-api-server ./app
          docker tag this-box-api-server dlrudtn108/this-box-api-server:${GITHUB_SHA::7}
          docker push dlrudtn108/this-box-api-server:${GITHUB_SHA::7}
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.AWS_EC2_PRIVATE_KEY }}
          envs: GITHUB_SHA
          script: |
            docker pull dlrudtn108/this-box-api-server:${GITHUB_SHA::7}
            docker tag this-box-api-server:${GITHUB_SHA::7} dlrudtn108/this-box-api-server
            docker stop server
            docker run -d --rm --name server -p 80:8080 this-box-api-server

